name: Lint and Test

on: push

jobs:
  dev-depends:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - id: cache-restore-dev-depends
        uses: actions/cache/restore@v4
        with:
          path: ./vendor
          key: dev-depends-php8.2-${{ hashFiles('composer.lock') }}

      - if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
        id: cache-save-dev-depends
        uses: actions/cache/save@v4
        with:
          path: ./vendor
          key: dev-depends-php8.2-${{ hashFiles('composer.lock') }}

  lint:
    needs: dev-depends

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - id: cache-restore-dev-depends
        uses: actions/cache/restore@v4
        with:
          path: ./vendor
          key: dev-depends-php8.2-${{ hashFiles('composer.lock') }}

      - run: ./vendor/bin/pint --test

      - run: ./vendor/bin/phpstan analyse --memory-limit=1G

  test:
    needs: dev-depends

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
          MYSQL_USER: ci_user
          MYSQL_PASSWORD: password

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - id: cache-restore-dev-depends
        uses: actions/cache/restore@v4
        with:
          path: ./vendor
          key: dev-depends-php8.2-${{ hashFiles('composer.lock') }}

      - run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - run: php artisan key:generate

      - run: php artisan migrate

      - run: php artisan test
